export const favorite_movies = [
  {
    adult: false,
    backdrop_path: "/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    belongs_to_collection: null,
    budget: 165000000,
    genres: [
      { id: 12, name: "Adventure" },
      { id: 18, name: "Drama" },
      { id: 878, name: "Science Fiction" },
    ],
    homepage: "http://www.interstellarmovie.net/",
    id: 157336,
    imdb_id: "tt0816692",
    original_language: "en",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    popularity: 100.217,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    production_companies: [
      {
        id: 923,
        logo_path: "/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png",
        name: "Legendary Pictures",
        origin_country: "US",
      },
      {
        id: 9996,
        logo_path: "/3tvBqYsBhxWeHlu62SIJ1el93O7.png",
        name: "Syncopy",
        origin_country: "GB",
      },
      {
        id: 13769,
        logo_path: null,
        name: "Lynda Obst Productions",
        origin_country: "",
      },
    ],
    production_countries: [
      { iso_3166_1: "GB", name: "United Kingdom" },
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2014-11-05",
    revenue: 675120017,
    runtime: 169,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    title: "Interstellar",
    video: false,
    vote_average: 8.3,
    vote_count: 26446,
  },
  {
    adult: false,
    backdrop_path: "/hmzvI2zS3a7DrhfVgIibohpNQLW.jpg",
    belongs_to_collection: null,
    budget: 0,
    genres: [{ id: 18, name: "Drama" }],
    homepage: "",
    id: 13384,
    imdb_id: "tt0064541",
    original_language: "en",
    original_title: "Kes",
    overview:
      "A young, English working-class boy spends his free time caring for and training his pet falcon.",
    popularity: 7.408,
    poster_path: "/r1FMq75irhsQBVGjXhPU4xA9SDo.jpg",
    production_companies: [
      {
        id: 1980,
        logo_path: null,
        name: "Woodfall Film Productions",
        origin_country: "",
      },
      {
        id: 27016,
        logo_path: null,
        name: "Kestrel Films Ltd.",
        origin_country: "",
      },
    ],
    production_countries: [{ iso_3166_1: "GB", name: "United Kingdom" }],
    release_date: "1970-04-03",
    revenue: 0,
    runtime: 110,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline:
      "They beat him.  They deprived him. they ridiculed him. They broke his heart but they couldn't break his spirit.",
    title: "Kes",
    video: false,
    vote_average: 7.5,
    vote_count: 270,
  },
  {
    adult: false,
    backdrop_path: "/2WyjkKudTkDgtZo9CIN8NoPGHRB.jpg",
    belongs_to_collection: null,
    budget: 10000000,
    genres: [
      { id: 35, name: "Comedy" },
      { id: 10749, name: "Romance" },
    ],
    homepage: "https://www.miramax.com/movie/amelie/",
    id: 194,
    imdb_id: "tt0211915",
    original_language: "fr",
    original_title: "Le Fabuleux Destin d'Amélie Poulain",
    overview:
      "At a tiny Parisian café, the adorable yet painfully shy Amélie accidentally discovers a gift for helping others. Soon Amelie is spending her days as a matchmaker, guardian angel, and all-around do-gooder. But when she bumps into a handsome stranger, will she find the courage to become the star of her very own love story?",
    popularity: 23.876,
    poster_path: "/vZ9NhNbQQ3yhtiC5sbhpy5KTXns.jpg",
    production_companies: [
      {
        id: 591,
        logo_path: "/q5I5RDwMEiqoNmfaJgd2LraEOJY.png",
        name: "France 3 Cinéma",
        origin_country: "FR",
      },
      {
        id: 592,
        logo_path: null,
        name: "Claudie Ossard Productions",
        origin_country: "",
      },
      {
        id: 4411,
        logo_path: null,
        name: "MMC Independent",
        origin_country: "",
      },
      { id: 12000, logo_path: null, name: "Tapioca Films", origin_country: "" },
      {
        id: 23446,
        logo_path: null,
        name: "Sofica Sofinergie 5",
        origin_country: "",
      },
      {
        id: 25020,
        logo_path: null,
        name: "Victoires Productions",
        origin_country: "",
      },
      {
        id: 104,
        logo_path: "/9aotxauvc9685tq9pTcRJszuT06.png",
        name: "Canal+",
        origin_country: "FR",
      },
      {
        id: 315,
        logo_path: "/hdu0sVxgtCuQud0xF8ZBiN7hEhY.png",
        name: "Filmstiftung Nordrhein-Westfalen",
        origin_country: "DE",
      },
      {
        id: 7248,
        logo_path: null,
        name: "Union Générale Cinématographique (UGC)",
        origin_country: "FR",
      },
      {
        id: 581,
        logo_path: "/pzJLNyKypqwAgLR4OjmaxA5WEjm.png",
        name: "UGC",
        origin_country: "FR",
      },
    ],
    production_countries: [
      { iso_3166_1: "FR", name: "France" },
      { iso_3166_1: "DE", name: "Germany" },
    ],
    release_date: "2001-04-25",
    revenue: 173921954,
    runtime: 122,
    spoken_languages: [
      { english_name: "French", iso_639_1: "fr", name: "Français" },
      { english_name: "Russian", iso_639_1: "ru", name: "Pусский" },
    ],
    status: "Released",
    tagline: "One person can change your life forever.",
    title: "Amélie",
    video: false,
    vote_average: 7.9,
    vote_count: 8979,
  },
  {
    adult: false,
    backdrop_path: "/ik2D3KqxFD0O0Bc3Wv1CZm8sOg8.jpg",
    belongs_to_collection: null,
    budget: 30000000,
    genres: [
      { id: 35, name: "Comedy" },
      { id: 18, name: "Drama" },
      { id: 10749, name: "Romance" },
      { id: 10402, name: "Music" },
    ],
    homepage: "http://www.lalaland.movie",
    id: 313369,
    imdb_id: "tt3783958",
    original_language: "en",
    original_title: "La La Land",
    overview:
      "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    popularity: 23.56,
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    production_companies: [
      {
        id: 491,
        logo_path: "/rUp0lLKa1pr4UsPm8fgzmnNGxtq.png",
        name: "Summit Entertainment",
        origin_country: "US",
      },
      {
        id: 33681,
        logo_path: "/dHx2nsV9AC7IBlKN2dk1FDImvOz.png",
        name: "Black Label Media",
        origin_country: "US",
      },
      {
        id: 10161,
        logo_path: null,
        name: "Gilbert Films",
        origin_country: "US",
      },
      {
        id: 53247,
        logo_path: null,
        name: "Impostor Pictures",
        origin_country: "US",
      },
      {
        id: 2527,
        logo_path: "/osO7TGmlRMistSQ5JZusPhbKUHk.png",
        name: "Marc Platt Productions",
        origin_country: "US",
      },
      {
        id: 1632,
        logo_path: "/cisLn1YAUuptXVBa0xjq7ST9cH0.png",
        name: "Lionsgate",
        origin_country: "US",
      },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2016-11-29",
    revenue: 446486224,
    runtime: 129,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Here's to the fools who dream.",
    title: "La La Land",
    video: false,
    vote_average: 7.9,
    vote_count: 13495,
  },
];
